const data={
    products: [{
        _id:'1',
        name:'Vintage Typewriter to post awesome stories about UI design and webdev.',
        category:'jardin',
        image:'/images/1.jpg',
        price:250,
        brand:'phoenix',
        countInStock:5,
        rating:4.5,
        numReviews:10,
        description:'Hipster Dev is busy coding away while styled in a camo jacket and orange beanie',
    },
    {
        _id:'2',
        name:'Lee Pucker design. Leather botinki for handsome designers. Free shipping.',
        category:'jardin',
        image:'/images/3.jpg',
        price:650.30,
        brand:'phoenix',
        countInStock:0,

        rating:4,
        numReviews:19000,
        description:'Everyones favorite design is finally here on a tee! The Pretty Girls Code crew-neck tee is available in a soft pink with red writing',
    },
    {
        _id:'3',
        name:'Timesaving kitten to save months on development. Playful, cute, cheap!',
        category:'jardin',
        image:'/images/4.jpg',
        price:450,
        brand:'phoenix',
        countInStock:2,

        rating:4.5,
        numReviews:2,
        description:'hight quality product',
    },
    {
        _id:'4',
        name:'Plastic useless plugs and tubes for high-fidelity prototyping. Fit & Eat!',
        category:'jardin',
        image:'/images/5.jpg',
        price:250,
        brand:'phoenix',
        countInStock:0,

        rating:4.5,
        numReviews:15,
        description:'Styled in a dashiki, Ruby Sis is listening to music while coding in her favorite language, Ruby!',
    },
    {
        _id:'5',
        name:'Creativity stimulating lotion. Drink every morning to generate better ideas!',
        category:'jardin',
        image:'/images/5.jpg',
        price:250,
        brand:'phoenix',
        countInStock:5,

        rating:4.5,
        numReviews:15,
        description:'Styled in a dashiki, Ruby Sis is listening to music while coding in her favorite language, Ruby!',
    },
    {
        _id:'6',
        name:'Prototyping items to create a lot if useless things...',
        category:'jardin',
        image:'/images/6.jpg',
        price:250,
        brand:'phoenix',
        countInStock:0,

        rating:4.5,
        numReviews:15,
        description:'Styled in a dashiki, Ruby Sis is listening to music while coding in her favorite language, Ruby!',
    },
    {
        _id:'7',
        name:'Professional teadrinking set for every designer and developer korl 150--ks',
        category:'jardin',
        image:'/images/7.jpg',
        price:250,
        brand:'phoenix',
        countInStock:5,

        rating:4.5,
        numReviews:15,
        description:'Styled in a dashiki, Ruby Sis is listening to music while coding in her favorite language, Ruby!',
    },
    {
        _id:'8',
        name:'Simply best item in town to shine bright with your Nine Inch Nails',
        category:'jardin',
        image:'/images/8.jpg',
        price:250,
        brand:'phoenix',
        countInStock:5,

        rating:4.5,
        numReviews:15,
        description:'Styled in a dashiki, Ruby Sis is listening to music while coding in her favorite language, Ruby!',
    },
    {
        _id:'9',
        name:'Simply best item in town to shine bright with your Nine Inch Nails',
        category:'jardin',
        image:'/images/9.jpg',
        price:250,
        brand:'phoenix',
        countInStock:5,

        rating:4.5,
        numReviews:15,
        description:'Styled in a dashiki, Ruby Sis is listening to music while coding in her favorite language, Ruby!',
    },
    {
        _id:'10',
        name:'KISTOCHKI & KRASIBO. Top cosmetics brand from Chelyabinsk is here!',
        category:'jardin',
        image:'/images/2.jpg',
        price:250,
        brand:'phoenix',
        countInStock:4,

        rating:4.5,
        numReviews:15,
        description:'Styled in a dashiki, Ruby Sis is listening to music while coding in her favorite language, Ruby!',
    },
  ],
};
export default data;